name: Release Astro
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Release Tacones
    runs-on: ubuntu-latest
    steps:
      - name: Check out ${{ github.sha }} from repository ${{ github.repository }}
        uses: actions/checkout@v2

      - name: Generate distribution zips
        id: release-zip
        run: |
          release=$(python .github/scripts/release.py)
          release="${release//'%'/'%25'}"
          release="${release//$'\n'/'%0A'}"
          release="${release//$'\r'/'%0D'}"
          echo ::set-output name=version::$release

      - name: Create Release on Github
        uses: softprops/action-gh-release@v1
        with:
          name: "Tacones - v${{ steps.release-zip.outputs.version }}"
          tag_name: ${{ steps.release-zip.outputs.version }}
          body: ${{ steps.get-changelog.outputs.body }}
          draft: false
          prerelease: false
          files: "dist/*.zip"
          token: ${{ secrets.GH_TOKEN }}
