name: Release Tacones
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Release Tacones
    runs-on: ubuntu-latest
    steps:
      - name: Check out ${{ github.sha }} from repository ${{ github.repository }}
        uses: actions/checkout@v2

      - name: Generate distribution zips
        id: release-zip
        run: |
          output=$(python .github/scripts/release.py)
          version=$(echo "$output" | jq -r '.version')
          name=$(echo "$output" | jq -r '.name')
          id=$(echo "$output" | jq -r '.id')
          dest=$(echo "$output" | jq -r '.dest')
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "NAME=$name" >> $GITHUB_ENV
          echo "ID=$id" >> $GITHUB_ENV
          echo "DEST=$dest" >> $GITHUB_ENV

      - name: Use release info
        run: |
          echo "The release version is $VERSION"
          echo "The addon name is $NAME"
          echo "The addon ID is $ID"
          echo "The destination path is $DEST"

      # - name: Create Release on Github
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     name: "Tacones - v${{ steps.release-zip.outputs.version }}"
      #     tag_name: ${{ steps.release-zip.outputs.version }}
      #     body: ${{ steps.get-changelog.outputs.body }}
      #     draft: false
      #     prerelease: false
      #     files: "dist/*.zip"
      #     token: ${{ secrets.GH_TOKEN }}

      - name: Deploy to external repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}

        with:
          # GitHub Action output files
          source-directory: output
          destination-github-username: ${{secrets.USER_NAME}}
          destination-repository-name: "Tacones-Repo"
          user-email: ${{secrets.USER_EMAIL}}
          commit-message: ":sparkles: Add addon to repository"
