name: Release Tacones
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Release Tacones
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIT_USER_NAME: ${{secrets.USER_NAME}}
      GIT_USER_EMAIL: ${{secrets.USER_EMAIL}}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      ADDON_REPOSITORY: Tacones-Repo
      ADDON: "plugin.video.tacones"
    steps:
      - name: Installing environment tools
        run: sudo snap install --classic hub

      - name: Configure Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Start deployment
        run: |
          # Deploying
          echo "Entering Git repo directory"
          cd ${{ github.workspace }}
          echo "Downloading deployment script"
          echo "pip-installing lxml"
          pip install lxml
          echo "Preparing ZIP"
          python .github/scripts/release.py -z
          echo "- Deploying to Kodi repository"
          python .github/scripts/release.py -r
      - name: Release on GitHub
        run: |
          echo "Entering Git repo directory"
          cd ${{ github.workspace }}
          echo "Getting assets"
          assets=()
          for asset in ./*.zip; do
            assets+=("-a" "${asset}")
          done
          echo "Getting add-on version"
          python .github/scripts/release.py -v
          git_tag="$(cat version)"
          echo "Releasing the kraken"
          hub release create "${assets[@]}" -m "Tacones-v${git_tag}" "Tacones-v${git_tag}"
